---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: "{{ var_all | default('all') }}"
  
  roles:
  - common

# Configure and deploy database servers.
- hosts: "{{ var_dbservers | default('dbservers') }}"
  vars_files:
    - group_vars/dbservers.yml
  roles:
  - db

  tags:
  - db

# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: "{{ var_webservers | default('webservers') }}"
  vars_files:
    - group_vars/webservers.yml
  roles:
  - base-apache
  - web
  
  tags:
  - web

# Configure and deploy the load balancer(s).
- hosts: "{{ var_lbservers | default('lbservers') }}"
  vars_files:
    - group_vars/lbservers.yml
  roles:
  - haproxy
  
  tags:
  - lb

# Configure and deploy the Nagios monitoring node(s).
- hosts: "{{ var_monitoring | default('monitoring') }}"
  
  roles:
  - base-apache
  - nagios
  
  tags:
  - monitoring
